### ISSUE TITLE
launcher use the default "packagesListUrl" instead of my

### ISSUE THREAD

**Issue by smenes** [hayleox/craftboot#1]
Hi
I use CraftBoot v1.0.1
i have enter the url for my launcher.properties
the .craftboot are created in my user directory and my launcher.properties are inside this folder.
so everything seem to work fine but my modpack does not appear in the list
I have only the vanilla 1.7.4 in the list (and this modpack is not working btw)

but if I edit the launcher.properties in the .jar ("C:\Users\Sylvain.craftboot\downcube.jar\launcher\1397363367648.jar")
and I change packagesListUrl by the good one, everything work fine. I have my modpack in the the list and it's work.

maybe I can share this launcher instead of the other one, but I don't think is the the way it's supose to work. also when we use this launcher it create all the file in the same directory :/

and sorry for my english, I'm french

**Comment by hayleox** [comment]
You actually have to upload the launcher.properties file to your web server and, when you start the launcher for the first time, enter the URL where that launcher.properties file is located (i.e. I have an example one uploaded at "http://oxguy3.github.io/craftboot-files/launcher.properties"). CraftBoot redownloads the launcher.properties file from that URL every time you start it, so if you just go and change it manually in the .craftboot folder, it'll get overridden when you start CraftBoot.

If you have already done entered a URL and want to change it now, you can either delete your .craftboot folder, or edit the ".craftbooturl" file.

EDIT: ~~think i might have misread your message, going to test something...~~ Nope, everything works as it should for me. Perhaps the URL you entered for your launcher.properties file was incorrect? (if you enter an invalid URL, I believe it will default to the launcher.properties file included in the launcher)

**Comment by smenes** [comment]
ok I have delete .craftboot
download and launch craftboot
When it asks for a url I use this one: http://games.downcube.fr/download/modpack/1.6.4/launcher.properties

and the modpack is not in the list http://i.imgur.com/0WZqHok.png

I use JRE 8 x64 btw

**Comment by hayleox** [comment]
Ah, after running around panicked looking for a bug with CRLF vs LF line breaks or a trailing line break or something like that, it turns out the problem is that the variable should actually be written "packageListUrl" not "packagesListUrl" in launcher.properties. I had it wrong in the sample version, my bad!

I tested and your modpack appears to work once that typo is corrected. (although you probably shouldn't include those sound files since they're copyrighted by Mojang; every file that's included with vanilla 1.6.4 will also be downloaded for your modpack, so you can just leave the sounds folder out of your src folder)

**Comment by smenes** [comment]
ha yes, it's working !

which soud files ? in the librairies folder ?
in this page http://confluence.skcraft.com/display/LAUN/Generating+a+Package+Manifest
he say to upload the entire libraries folder to a web server 
"You don't actually have to upload everything, but it is the easiest way to not miss something important. In actuality, you only need to upload libraries added by Forge."
but I don't know which one are for forge

thanks for your quick reply, it's appreciate

EDIT: ho I see, it's in the custom_jar.jar. how to use forge without this ?

**Comment by hayleox** [comment]
No prob, glad to hear it! I was talking about the /sounds folder that goes into your .minecraft folder. Like, you know how you have a dist and src folder where you compile the modpack? I'm talking about the sounds folder inside the src folder. Since those sounds are all part of vanilla 1.6.4, they'll automatically get downloaded from Mojang's servers, so having them download from your servers instead just creates an unnecessary copyright issue.

**Comment by smenes** [comment]
heu, maybe i'm crazy but I don't have sound folder in src

is there a way to change the window title and the boots icon ?

**Comment by hayleox** [comment]
Never mind, I saw the sounds files downloading and assumed they were coming from your server, but they are indeed downloading from Mojang's servers. (attention to detail is apparently not something I'm great at)

**Comment by smenes** [comment]
no problem, thanks again

**Comment by hayleox** [comment]
No prob, glad I could help!
