### ISSUE TITLE
no minecraft folder in instance folder

### ISSUE THREAD

**Issue by smenes** [hayleox/craftboot#2]
Hi
I have try to make a vanilla modpack for 1.7.8 but if you put nothing inside your src folder, the launcher does not create the minecraft folder in your instance.

when I do the same with a blank .txt file in src folder everything work fine

http://games.downcube.fr/download/launcher.properties

**Comment by hayleox** [comment]
Vanilla with this launcher is a little goofy, but I got it to work alright
for me. It won't create an objects folder because there aren't any extra
files needed for vanilla, but it'll create the manifest.json file, which is
all you need. I have a vanilla setup in the sample files at
http://github.com/oxguy3/craftboot-files if you want to copy mine (I think
I put a 1.7.5 and 1.7.8 folder there).

**Comment by smenes** [comment]
same probleme with your files http://pastebin.com/B5gSdTFN the minecraft folder it's not created
anyways it's not a big issue, we just need to put something in src

**Comment by hayleox** [comment]
Oh must just be an issue with the launcher. I'll look into it, but yeah for
the time being, you might just include a servers.dat file with your server
included on it, so that you can both work around the bug and save your
players a step (though be sure to define it as a user file in your
modpack.json so that they can add other servers).

Since the issue is with the launcher rather than with the bootstrapper
itself, CraftBoot will be able to automatically download an updated version
of the launcher when I put one out, so no need to wait to distribute until
there's a fix.

**Comment by smenes** [comment]
ok thanks

**Comment by hayleox** [comment]
I made an update to the launcher that fixes the bug. Next time you run CraftBoot, the launcher will have an "Update launcher" button that will allow you to download the new version.

**Comment by smenes** [comment]
thanks, but now it's always "pending update" http://i.imgur.com/eVJBNoO.png

EDIT: forget it, bad version number in my manifest.json

**Comment by hayleox** [comment]
Hmmm, I'm not getting any problem like that; did you make any changes
within your minecraft folder? EDIT: Oh okay awesome.
